# Generated by Django 5.0.6 on 2026-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="api_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="drone",
            name="last_alt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drone",
            name="last_battery",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drone",
            name="last_heading",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drone",
            name="last_signal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
